---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files: 
    - vars/vars.yaml
  tasks:
    # setup auth:
    - name: Use API Token if defined
      set_fact:
        authorization: "Bearer {{ api_token }}"
      when: api_token is defined

    - name: Use username/password if defined
      set_fact:
        authorization: "Basic {{ (username + ':' + password) | b64encode }}"
      when: username is defined and password is defined

    - include_tasks: tasks/testing.yaml
      when: activity == 'testing'

    - include_tasks: tasks/acs-config.yaml
      when: activity == "acs_config"

    - include_tasks: tasks/team-access.yaml
      when: activity == 'team_access'
